POST http://localhost:3500/users
Content-Type: application/json

{
    "id": "userId2",
    "name": "테스트2",
    "password": "qwe09123",
    "birthday": {
        "year": 1997,
        "month": 8,
        "day": 31
    },
    "phoneNumber": "01000000003"
}

###

GET http://localhost:3500/users/1
Accept: application/json

###

POST http://localhost:3500/users
Content-Type: application/json

{
    "id": "anonymous",
    "name": "익명이다",
    "password": "qwe09123",
    "birthday": {
        "year": 1995,
        "month": 3,
        "day": 22
    },
    "phoneNumber": "01044444444"
}

###
