#!/usr/bin/env node
const app = require('../app/app');
const db = require('../app/db');
const environment = require('../environment');


async function start() {
    await db.authenticate();

    app.listen(environment.config.PORT, () => {
        console.log('Server is running.');
    });
}

start().catch(error => console.error(error));
